### ISSUE TITLE
FYI: I could install, eventually, but it downgraded a lot of packages

### ISSUE THREAD

**Issue by PallHaraldsson** [ICHEC/PicoQuant.jl#2]
Hi, I was just curious what this package is about (probably not related to quantitative finance? I'm not familiar with QuantEx, only QuantLib.jl). You may want to edit your README to say a bit more to clarify what's it for quantum M vs quant finance..., I'm not saying you need to clarify with a longer name.

A.
I had to remove Winston (and unsure it's a problem at that package or yours): https://github.com/JuliaGraphics/Winston.jl/issues/304

Then I could install it, but it e.g. downgraded plotting packages GR and gnuplot.jl.

The sesond time around (without Revise.jl installed) deleting the package and installing again it's (mostly) normal:

```
[..]
  [a3f928ae] ↑ Fontconfig_jll v2.13.1+11 ⇒ v2.13.1+12
  [0c68f7d7] + GPUArrays v3.4.1
  [61eb1bfa] + GPUCompiler v0.2.0
  [aa1b3936] + GraphIO v0.5.0
  [aacddb02] ↑ JpegTurbo_jll v2.0.1+0 ⇒ v2.0.1+1
  [8ac3fa9e] + LRUCache v1.1.0
  [c8ffd9c3] ↑ MbedTLS_jll v2.16.6+0 ⇒ v2.16.6+1
  [626554b9] + MetaGraphs v0.6.5
  [4536629a] ↑ OpenBLAS_jll v0.3.9+4 ⇒ v0.3.9+5
```

I found it a bit strange that it upgraded some packages, after I installed the package minutes ago.

With Revise.jl installed, and installing your package the first time around I see lots of strangeness (have seen before, ignore it, seems like a bug in Revise), but also downgrading:

```
 [82e4d734]     - ImageIO v0.2.0end

@ eval [dc211083]  ↓ Gnuplot v1.3.0 ⇒ v1.0.0begin

  [2]  [13f3f980] append_any↓ CairoMakie v0.2.8 ⇒ v0.2.4(
:: Any [324d7699] , ↑ CategoricalArrays v0.7.7 ⇒ v0.8.1::
Vararg { [082447d4] Any↑ ChainRules v0.6.5 ⇒ v0.7.2,
N } [d360d2e6]  where ↑ ChainRulesCore v0.8.0 ⇒ v0.9.1N
)  at  [3da002f7] /home/pharaldsson_sym/.julia/packages/JuliaInterpreter/sgtJc/src/JuliaInterpreter.jl:34↓ ColorTypes v0.10.3 ⇒ v0.9.1)
Revise . [5ae59095] LogRecord↓ Colors v0.12.2 ⇒ v0.11.2(
Error ,  [861a8166] evaluation error starting at /home/pharaldsson_sym/.julia/packages/RecipesPipeline/wolJ9/src/utils.jl:211+ Combinatorics v1.0.2, 


The applicable method may be too new: running in world age 28030, while current world is 29045. 
Closest candidates are:
  (::RecipesPipeline.var"#96#97")(::Any) at none:0 (method too new to be called from this world context.) [d8418881] 
Stacktrace:↑ Intervals v1.3.0 ⇒ v1.3.4

 [1]  iterate [98e50ef6] (↑ JuliaFormatter v0.6.2 ⇒ v0.6.5::
Base . [aa1ae85d] Generator↑ JuliaInterpreter v0.7.21 ⇒ v0.7.23{
UnitRange { [929cbde3] Int64+ LLVM v1.7.0}
, RecipesPipeline [8ac3fa9e] .+ LRUCache v1.1.0var
"#96#97" } [194296ae] )↑ LibPQ v1.2.0 ⇒ v1.4.1 at 
./generator.jl:47 
 [472f376f]  [2] ↑ LoadFlint v0.1.3 ⇒ v0.3.0append_any
( :: [bdcacae8] Any↑ LoopVectorization v0.7.8 ⇒ v0.8.9, 
:: Vararg [6f1432cf] {↑ LoweredCodeUtils v0.4.5 ⇒ v0.4.6Any
, N [3a97d323] }+ MPFR_jll v4.0.2+2 where 
N ) [ee78f7c6]  at ↓ Makie v0.11.0 ⇒ v0.10.0/home/pharaldsson_sym/.julia/packages/JuliaInterpreter/sgtJc/src/JuliaInterpreter.jl:34


  [2edaba10] ↓ Nemo v0.17.5 ⇒ v0.17.0
  [f57f5aa1] - PNGFiles v0.2.1
  [b873ce64] - ReplMaker v0.2.3
```

B.
You may want to look into "invalidations" with Snoopcompile.jl, but I'm not sure it's the package fault or some or many of its dependencies:

```
$ julia --startup-file=no -O0 -q

julia> @time using PicoQuant
  8.513975 seconds (12.89 M allocations: 720.266 MiB, 4.45% gc time)

julia> @time using PicoQuant
  0.801952 seconds (2.10 M allocations: 105.302 MiB, 3.39% gc time)

julia> @time using PicoQuant
  0.000507 seconds (712 allocations: 42.000 KiB)

julia> versioninfo()
Julia Version 1.6.0-DEV.203
Commit 4e2fb5c72c (2020-06-09 12:13 UTC)
```

**Comment by nmoran** [comment]
Hi @PallHaraldsson, the package is related to quantum circuit simulation (the "Quant" part) on exa-scale HPC machines (the "Ex" part), part of the quantex project (https://github.com/ichec/quantex). This is good feedback about making the readme more explanatory so we will aim to do this shortly.

Regarding these installation issues, I have not come across any of these but have only been testing with stable release versions and will a clean environments. Our gitlab CI system currently only tests with versions 1.3.1 and 1.4.2 and the installation works fine for both of these. We will look to add a test with nightly to this also. We had hoped to still support the LTS version but this was restricting package versions quite a lot. In general for this version, there are many dependencies which are not strictly required, or are only required for certain tasks or ways of using. I would also like to reduce these to the minimum required for the main use cases and maybe include environment files for the additional use cases in other folders (e.g. have IJulia and other notebook requirements in the nb folder).

Regarding the specific issues you raise
A. Winston is not a dependency, nor is Revise so I am guessing this is an issue when installing into an environment that already contains these packages? Do you have any suggestions on how we should address or mitigate these?

B. Is the issue here that everything is not precompiled on the first import? Will hopefully get some time to look into this with snoopcompile (but it is unlikely to happen for a week or two).

**Comment by PallHaraldsson** [comment]
FYI: I'm not saying the package doesn't work, it installs on 1.6 and probably works. I just didn't go further than the using part, wouldn't know where to go next... I just noticed packages downgrading (a common problem, I wish Julia would give a warning and you could choose to abort) and it may not be a problem in your Project.toml file, it could be in your dependencies (or just in unrelated packages I use).

Interesting it's for exascale, the new top supercomputer goes that far, for some benchmarks (only for AI? reduced precision), but not on Linpack. And is Arm-based, and 2.8 times faster than the previous top supercomputer.
